version : '3.8'
#container -> service
services:
  yangkang_data:
    image: mysql:8.0.28
    container_name: yangkang_mysql
    ports:
      - "3310:3306"
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - yk-network
    environment:
      MYSQL_USER: haiph1210
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: yangkang_data
#      COMMON
#  common:
#    container_name: eureka
#    build:
#      context: .
#      dockerfile: common/DockerFile
# EUREKA
  eureka-app:
    container_name: eureka
    build:
      context: .
      dockerfile: eureka-service/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - yk-network
#API-GATEWAY
#  gateway-service:
#    container_name: api-gateway
#    build:
#      context: .
#      dockerfile: api-gateway/Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - yk-network

# User-service
#  user-service-container:
#    image: haiph1210/user-service-image:v1.0.0
#    container_name: user-service-container
#    ports:
#      - 8001:8001
#    volumes:
#      - ./:/app
#    networks:
#      - yk-network
#Create Network
networks:
  yk-network:
    name: yangkang-data-app
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:



