version: '3.5'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - yk-network

networks:
  yk-network:
    name: yangkang-data-app