FROM openjdk:8-jdk-alpine
COPY ./worklog-service/target/worklog-service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-Deureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka","-jar","-Xmx384m","-Dspring.profiles.active=prod","worklog-service-0.0.1-SNAPSHOT.jar"]