server:
  port: 8762

eureka:
  instance:
    hostname: localhost

spring:
  #  main:
  #    web-application-type: reactive
  application:
    name: api-gateway
    cloud:
      gateway:
        routes:
          - id: menu-service
            uri: lb://menu-service
            predicates:
              - Path=/api/menu/**
              - Path=/api/combo/**
              - Path=/api/order/**
              - Path=/api/payment/**
              - Path=/api/discount/**
          - id: user-service
            uri: lb://user-service/
            predicates:
              - Path=/api/person/**
          - id: restaurant-service
            uri: lb://restaurant-service
            predicates:
              - Path=/restaurant/**
          - id: mails
            uri: lb://mail-service
            predicates:
              - Path=/mail/**