server:
  port: 8762

eureka:
  instance:
    hostname: localhost

spring:
  #  main:
  #    web-application-type: reactive
  application:
    name: api-gateway
    cloud:
      gateway:
        routes:
          - id: auth-service
            uri: http://localhost:8080
            predicates:
              -Path=/api/auth/**
          - id: menu-service
            uri: http://localhost:8000/
            predicates:
              - Path=/api/menu/**
              - Path=/api/combo/**
              - Path=/api/order/**
              - Path=/api/payment/**
              - Path=/api/discount/**
          - id: user-service
            uri: lb://user-service/
            predicates:
              - Path=/api/person/**
          - id: restaurant-service
            uri: lb://restaurant-service
            predicates:
              - Path=/restaurant/**
          - id: mail-service
            uri: http://localhost:8003/
            predicates:
              - Path=/api/email/**