server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      global cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        #        EMAIL-SERVICE
        - id: email
          uri: lb://mail-service
          predicates:
            - Path=/api/email/**

        #        MENU-SERVICE
        - id: menu
          uri: lb://menu-service
          predicates:
            - Path=/api/menu/**
          filters:
            - AuthenticationFilter

        - id: combo
          uri: lb://menu-service
          predicates:
            - Path=/api/combo/**
          filters:
            - AuthenticationFilter


        - id: order
          uri: lb://menu-service
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter

        - id: payment
          uri: lb://menu-service
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter

        - id: discount
          uri: lb://menu-service
          predicates:
            - Path=/api/discount/**
          filters:
            - AuthenticationFilter

        #        Restaurant-Serivce
        - id: info
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurant/info/**
          filters:
            - AuthenticationFilter

        - id: detail
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurant/detail/**
          filters:
            - AuthenticationFilter

        - id: masterial
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurant/masterial/**
          filters:
            - AuthenticationFilter
        - id: form
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurant/form/**
          filters:
            - AuthenticationFilter

        #        USER-SERVICE
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter

        - id: authentication
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

        #          AUTH-SERVICE
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/authenticate/**




